# Generated by Django 6.0.1 on 2026-02-28 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_feature_proj_layer_idx_features_project_24b9e2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_id', models.CharField(max_length=255)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'layer_weights',
            },
        ),
        migrations.RenameField(
            model_name='project',
            old_name='completion_percentage',
            new_name='standard_completion',
        ),
        migrations.AddField(
            model_name='feature',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerweight',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_weights', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='layerweight',
            index=models.Index(fields=['project', 'layer_id'], name='layer_weigh_project_c73604_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='layerweight',
            unique_together={('project', 'layer_id')},
        ),
    ]
