# Generated by Django 6.0.1 on 2026-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_layerweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feature_photos/%Y/%m/%d/'),
        ),
    ]
