# Generated by Django 6.0.1 on 2026-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_layerweight_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_project_24b9e2_idx',
            old_name='feature_proj_layer_idx',
        ),
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_layer_i_335aee_idx',
            old_name='feature_layer_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_status_b4cdda_idx',
            old_name='feature_status_idx',
        ),
        migrations.AddField(
            model_name='feature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feature_photos/%Y/%m/%d/'),
        ),
    ]
