# Generated by Django 5.1.15 on 2026-07-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_layerfieldconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_project_24b9e2_idx',
            old_name='feature_proj_layer_idx',
        ),
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_layer_i_335aee_idx',
            old_name='feature_layer_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feature',
            new_name='features_status_b4cdda_idx',
            old_name='feature_status_idx',
        ),
    ]
