# Generated by Django 5.1.15 on 2026-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_feature_proj_layer_idx_features_project_24b9e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='edited_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
