# Generated by Django 5.1.15 on 2026-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_feature_edited_at_feature_edited_by_feature_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_ftth_project_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
