# Generated by Django 5.1.15 on 2026-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_source_ftth_project_id_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('assigned', 'Assigned'), ('active', 'Active'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
