# Generated by Django 5.1.15 on 2026-08-12 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSurveyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number')),
                ('hld_project_id', models.CharField(help_text='Source HLD project ID', max_length=64)),
                ('total_changes', models.PositiveIntegerField(default=0)),
                ('approved_changes', models.PositiveIntegerField(default=0)),
                ('rejected_changes', models.PositiveIntegerField(default=0)),
                ('approved_data', models.JSONField(help_text='Complete approved survey dataset')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for LLD'), ('used_for_lld', 'Used for LLD')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lld_run_id', models.CharField(blank=True, help_text='LLD run ID if used', max_length=64)),
                ('lld_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_approved_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_survey_versions', to='projects.project')),
            ],
            options={
                'db_table': 'approved_survey_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['project', 'status'], name='approved_su_project_91c974_idx'), models.Index(fields=['version_number'], name='approved_su_version_c464d3_idx')],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SurveyChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('geometry', 'Geometry Change'), ('attribute', 'Attribute Change'), ('new_feature', 'New Feature'), ('removed_feature', 'Removed Feature')], max_length=20)),
                ('layer_name', models.CharField(max_length=255)),
                ('feature_id_display', models.CharField(help_text='Display ID for the feature', max_length=255)),
                ('original_geometry', models.JSONField(blank=True, help_text='Original HLD geometry', null=True)),
                ('original_attributes', models.JSONField(blank=True, help_text='Original HLD attributes', null=True)),
                ('proposed_geometry', models.JSONField(blank=True, help_text='Proposed survey geometry', null=True)),
                ('proposed_attributes', models.JSONField(blank=True, help_text='Proposed survey attributes', null=True)),
                ('changed_field', models.CharField(blank=True, help_text='Name of changed attribute', max_length=255)),
                ('original_value', models.JSONField(blank=True, help_text='Original field value', null=True)),
                ('proposed_value', models.JSONField(blank=True, help_text='Proposed field value', null=True)),
                ('reason', models.TextField(help_text='Reason for the change')),
                ('engineer_notes', models.TextField(blank=True, help_text='Additional notes from engineer')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction')], default='pending_review', max_length=20)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changes', to=settings.AUTH_USER_MODEL)),
                ('original_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_changes_as_original', to='projects.feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_changes', to='projects.project')),
                ('proposed_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_changes_as_proposed', to='projects.feature')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='survey_chan_project_ef5ccb_idx'), models.Index(fields=['change_type'], name='survey_chan_change__cfc6f9_idx'), models.Index(fields=['layer_name'], name='survey_chan_layer_n_8a5a8a_idx')],
            },
        ),
    ]
