# Generated by Django 5.1.15 on 2026-08-13 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0013_approvedsurveyversion_surveychange'),
    ]

    operations = [
        # The ``project`` column is dropped below, so the composite index that
        # leads with it has to go first. SQLite rebuilds the whole table for a
        # RemoveField and re-creates every index from the model state, so an
        # index on a column that no longer exists makes the rebuild fail with
        # "FieldDoesNotExist: NewSurveyChange has no field named 'project'"
        # (PostgreSQL never hit this — RemoveField there is a plain
        # ALTER TABLE ... DROP COLUMN, so nothing is rebuilt.)
        migrations.RemoveIndex(
            model_name='surveychange',
            name='survey_chan_project_ef5ccb_idx',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='original_feature',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='project',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='proposed_feature',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='ApprovedSurveyVersion',
        ),
        migrations.DeleteModel(
            name='SurveyChange',
        ),
    ]
