# Generated by Django 5.1.15 on 2026-08-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_approvedsurveyversion_surveychange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveychange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='original_feature',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='project',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='proposed_feature',
        ),
        migrations.RemoveField(
            model_name='surveychange',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='ApprovedSurveyVersion',
        ),
        migrations.DeleteModel(
            name='SurveyChange',
        ),
    ]
