# Generated by Django 5.1.15 on 2026-08-13 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_surveychange_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProjectLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_id', models.CharField(max_length=255)),
                ('layer_name', models.CharField(blank=True, default='', max_length=255)),
                ('feature_count', models.IntegerField(default=0)),
                ('survey_feature_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='projects.project')),
            ],
            options={
                'db_table': 'project_layers',
                'unique_together': {('project', 'layer_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('planner', 'Planner'), ('engineer', 'Field Engineer'), ('reviewer', 'LLD Reviewer'), ('contractor', 'Contractor'), ('observer', 'Observer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_members',
                'unique_together': {('project', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('hld', 'HLD'), ('survey', 'Survey'), ('lld', 'LLD')], max_length=10)),
                ('event', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', help_text='Feature id / run version this event concerns', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='projects.project')),
            ],
            options={
                'db_table': 'stage_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'stage'], name='stage_event_project_f477f4_idx')],
            },
        ),
    ]
