# Generated by Django 5.1.15 on 2026-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ftth_lld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lldrun',
            name='mode',
            field=models.CharField(
                choices=[
                    ('verify', 'Verify (apply survey changes)'),
                    ('replan', 'Full re-plan (re-run design algorithm)'),
                ],
                default='verify',
                max_length=20,
            ),
        ),
    ]
