# Generated by Django 5.1.15 on 2026-07-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FtthProject',
            fields=[
                ('project_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('stage_name', models.CharField(blank=True, default='', max_length=255)),
                ('stage_index', models.IntegerField(default=0)),
                ('stage_count', models.IntegerField(default=6)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('excel_filename', models.CharField(blank=True, default='', max_length=255)),
                ('roads_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ftth_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
