# Generated by Django 5.1.15 on 2026-08-12 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftth_hld', '0002_ftthproject_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSurveyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('hld_version', models.CharField(blank=True, default='', max_length=32)),
                ('dataset', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ftth_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_survey_versions', to='ftth_hld.ftthproject')),
            ],
            options={
                'db_table': 'ftth_approved_survey_versions',
                'ordering': ['-created_at'],
                'unique_together': {('ftth_project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LldRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lld_version', models.CharField(max_length=32)),
                ('hld_version', models.CharField(blank=True, default='', max_length=32)),
                ('algorithm_version', models.CharField(blank=True, default='', max_length=64)),
                ('input_dataset_version', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('outputs', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('approved_survey_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lld_runs', to='ftth_hld.approvedsurveyversion')),
                ('ftth_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lld_runs', to='ftth_hld.ftthproject')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ftth_lld_runs',
                'ordering': ['-run_date'],
            },
        ),
    ]
