# Generated by Django 5.1.15 on 2026-08-13 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ftth_hld', '0003_approvedsurveyversion_lldrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtthLayer',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('geojson', models.JSONField(default=dict)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'ftth_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hld_layers',
                        to='ftth_hld.ftthproject',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_hld_layers',
                'ordering': ['name'],
                'unique_together': {('ftth_project', 'name')},
            },
        ),
    ]
