# Generated by Django 5.1.15 on 2026-08-13 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftth_hld', '0004_ftthlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lldrun',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lldrun',
            name='validation',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='LldLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('geojson', models.JSONField(default=dict)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lld_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='ftth_hld.lldrun')),
            ],
            options={
                'db_table': 'ftth_lld_layers',
                'ordering': ['name'],
                'unique_together': {('lld_run', 'name')},
            },
        ),
    ]
