# Generated by Django 5.1.15 on 2026-08-13 11:53
#
# State-only migration: the LLD models (ApprovedSurveyVersion, LldRun,
# LldLayer) moved to the ``ftth_lld`` app. Their tables already exist with
# data, so this migration only updates Django's migration state and performs
# NO database operations.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ftth_hld', '0005_lldrun_progress_lldrun_validation_lldlayer'),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name='lldrun',
            name='approved_survey_version',
        ),
        migrations.AlterUniqueTogether(
            name='lldlayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lldlayer',
            name='lld_run',
        ),
        migrations.RemoveField(
            model_name='lldrun',
            name='ftth_project',
        ),
        migrations.RemoveField(
            model_name='lldrun',
            name='run_by',
        ),
        migrations.DeleteModel(
            name='ApprovedSurveyVersion',
        ),
        migrations.DeleteModel(
            name='LldLayer',
        ),
        migrations.DeleteModel(
            name='LldRun',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
