# Generated by Django 5.1.15 on 2026-08-13 16:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ftth_hld', '0006_remove_lldrun_approved_survey_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqRate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('item_code', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(blank=True, default='', max_length=60)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('material_rate', models.FloatField(default=0.0)),
                ('labour_rate', models.FloatField(default=0.0)),
                ('rent_rate', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ftth_boq_rates',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='BoqSnapshot',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('boq_json', models.JSONField(default=list)),
                ('bom_json', models.JSONField(default=list)),
                ('boq_totals', models.JSONField(default=dict)),
                ('bom_totals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                (
                    'ftth_project',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='boq_snapshot',
                        to='ftth_hld.ftthproject',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_boq_snapshots',
            },
        ),
    ]
