# Generated by Django 5.1.15 on 2026-08-14 14:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ftth_hld', '0007_boqrate_boqsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitAuthority',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'authority_type',
                    models.CharField(
                        choices=[
                            ('MUNICIPALITY', 'Municipality / Gemeinde'),
                            ('ROAD', 'Road authority (Straßenbaulastträger)'),
                            ('RAIL', 'Railway operator (DB / regional rail)'),
                            ('WATER', 'Water authority'),
                            ('ENVIRONMENTAL', 'Environmental agency'),
                            ('PRIVATE', 'Private landowner'),
                            ('TELECOM', 'Telecom right-of-way'),
                        ],
                        max_length=20,
                    ),
                ),
                ('country', models.CharField(default='DE', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('contact', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ftth_permit_authorities',
                'ordering': ['country', 'region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermitMatrix',
            fields=[
                (
                    'permit_id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('route_section', models.CharField(max_length=128)),
                ('layer', models.CharField(max_length=64)),
                ('permit_type', models.CharField(max_length=64)),
                ('municipality', models.CharField(blank=True, default='', max_length=128)),
                ('rule_version', models.CharField(blank=True, default='', max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('blocks_construction', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_required', 'Not required'),
                            ('identified', 'Identified'),
                            ('evidence_required', 'Evidence required'),
                            ('ready', 'Ready'),
                            ('submitted', 'Submitted'),
                            ('under_review', 'Under review'),
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('closed', 'Closed'),
                        ],
                        default='identified',
                        max_length=24,
                    ),
                ),
                ('readiness_pct', models.IntegerField(default=0)),
                ('evidence', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=dict)),
                ('analysis_notes', models.TextField(blank=True, default='')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, default='')),
                ('revision', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'authority',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='permits',
                        to='permits.permitauthority',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='permits',
                        to='ftth_hld.ftthproject',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_permit_matrix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('event', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'permit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='permits.permitmatrix',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_permit_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('DRAWING', 'Route drawing'),
                            ('CROSS_SECTION', 'Trench cross-section'),
                            ('SCHEDULE', 'Chamber / cabinet schedule'),
                            ('TMP', 'Traffic management plan'),
                            ('FORM', 'Permit application form'),
                            ('REPORT', 'Report'),
                        ],
                        default='REPORT',
                        max_length=32,
                    ),
                ),
                (
                    'file',
                    models.FileField(blank=True, null=True, upload_to='permit_documents/%Y/%m/'),
                ),
                ('url', models.URLField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'permit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='package_files',
                        to='permits.permitmatrix',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_permit_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitRule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('rule_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('layer_a', models.CharField(max_length=64)),
                ('layer_b', models.CharField(blank=True, default='', max_length=64)),
                ('operator', models.CharField(default='INTERSECTS', max_length=32)),
                (
                    'required_level',
                    models.CharField(
                        choices=[('REQUIRED', 'Required'), ('POTENTIAL', 'Potentially required')],
                        default='POTENTIAL',
                        max_length=16,
                    ),
                ),
                ('evidence_required', models.JSONField(default=list)),
                ('blocks_construction', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'authority',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rules',
                        to='permits.permitauthority',
                    ),
                ),
            ],
            options={
                'db_table': 'ftth_permit_rules',
                'ordering': ['rule_id'],
            },
        ),
        migrations.AddField(
            model_name='permitmatrix',
            name='rule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='permits',
                to='permits.permitrule',
            ),
        ),
        migrations.AddIndex(
            model_name='permitmatrix',
            index=models.Index(fields=['project', 'status'], name='ftth_permit_project_4e1510_idx'),
        ),
        migrations.AddIndex(
            model_name='permitmatrix',
            index=models.Index(
                fields=['project', 'route_section'], name='ftth_permit_project_b8d39f_idx'
            ),
        ),
    ]
