# Generated by Django 5.1.15 on 2026-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitmatrix',
            name='permit_group',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
