# Generated by Django 5.1.15 on 2026-08-18 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftth_hld', '0007_boqrate_boqsnapshot'),
        ('permits', '0002_permitmatrix_permit_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permit_type', models.CharField(max_length=64)),
                ('permit_group', models.CharField(blank=True, default='', max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='submitted', max_length=24)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('conditions', models.TextField(blank=True, default='')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=0)),
                ('package_version', models.IntegerField(blank=True, null=True)),
                ('sync_source', models.CharField(default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='permits.permitauthority')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_submissions', to='ftth_hld.ftthproject')),
            ],
            options={
                'db_table': 'ftth_permit_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='permitmatrix',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_rows', to='permits.permitsubmission'),
        ),
        migrations.AddIndex(
            model_name='permitsubmission',
            index=models.Index(fields=['project', 'status'], name='ftth_permit_project_f7265e_idx'),
        ),
        migrations.AddIndex(
            model_name='permitsubmission',
            index=models.Index(fields=['authority', 'status'], name='ftth_permit_authori_ae2344_idx'),
        ),
    ]
