"""Auto-populated permit application forms.

One HTML form per permit matrix row, pre-filled from the project, the
authority, the rule and the recorded evidence — the deterministic
permit-determination data (never LLM-generated). Forms are printable and
carry a traceability footer (rule id + version + analysis timestamp).
"""

from __future__ import annotations

import html as _html
from datetime import datetime, timezone
from typing import Any

from . import data


def _e(v: Any) -> str:
    return _html.escape("" if v is None else str(v))


def _evidence_rows(pm) -> list[tuple[str, str]]:
    ev = pm.evidence or {}
    rows = []
    for key, val in ev.items():
        if isinstance(val, dict):
            present = val.get("present")
            value = val.get("value")
            if present and value is not None:
                rows.append((key.replace("_", " ").title(), _e(value)))
            elif present:
                rows.append((key.replace("_", " ").title(), "Recorded"))
            else:
                rows.append((key.replace("_", " ").title(), "—"))
        else:
            rows.append((key.replace("_", " ").title(), _e(val)))
    return rows


def _form_page(pm, project_name: str) -> str:
    authority = pm.authority
    rule = pm.rule
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status = pm.get_status_display() if hasattr(pm, "get_status_display") else str(pm.status)

    def field(label: str, value: str) -> str:
        return (
            f'<tr><th style="text-align:left;width:200px;padding:6px 8px;'
            f'border:1px solid #E5E7EB;background:#F9FAFB;font-size:12px;">'
            f'{_e(label)}</th>'
            f'<td style="padding:6px 8px;border:1px solid #E5E7EB;font-size:12px;">'
            f'{value}</td></tr>'
        )

    rows = "".join([
        field("Project", _e(project_name)),
        field("Project ID", _e(pm.project_id)),
        field("Permit Type", _e(pm.permit_type)),
        field("Route Section", _e(pm.route_section)),
        field("Layer", _e(pm.layer)),
        field("Municipality", _e(pm.municipality or "To be resolved")),
        field("Authority", _e(authority.name if authority else "Unassigned")),
        field("Authority Code", _e(authority.code if authority else "—")),
        field("Required Level", _e(rule.required_level if rule else "")),
        field("Status", _e(status)),
        field("Readiness", f"{pm.readiness_pct}%"),
        field("Conditions", _e(pm.conditions or "—")),
        field("Comments", _e(pm.comments or "—")),
    ])

    ev_rows = "".join(
        f'<tr><td style="padding:4px 8px;border:1px solid #E5E7EB;font-size:12px;">'
        f'{k}</td><td style="padding:4px 8px;border:1px solid #E5E7EB;font-size:12px;">'
        f'{v}</td></tr>'
        for k, v in _evidence_rows(pm)
    ) or '<tr><td colspan="2" style="padding:6px 8px;font-size:12px;color:#6B7280;">No evidence recorded yet.</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<title>Permit Application — {_e(pm.permit_type)}</title></head>
<body style="font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#111827;">
  <h2 style="margin:0 0 4px;">Permit Application Form</h2>
  <p style="margin:0 0 16px;color:#6B7280;font-size:12px;">Auto-generated by the FTTH permit engine — deterministic data only.</p>
  <table style="border-collapse:collapse;width:100%;">{rows}</table>
  <h3 style="margin:20px 0 8px;font-size:14px;">Evidence</h3>
  <table style="border-collapse:collapse;width:100%;">{ev_rows}</table>
  <p style="margin-top:24px;font-size:10px;color:#9CA3AF;">
    Traceability: rule {_e(rule.rule_id if rule else '—')} v{_e(rule.version if rule else '—')} · generated {now}
  </p>
</body></html>
"""


def application_forms(project_id: str, project_name: str) -> list[dict[str, Any]]:
    """One HTML application form per permit row in the matrix."""
    forms = []
    for pm in data.permit_rows(project_id):
        if not pm.rule or pm.rule.rule_id == "UTILITY_REUSE_001":
            # Informational coexistence rows don't get an application form.
            continue
        slug = (pm.permit_type or "permit").lower().replace(" ", "_")
        rid = (pm.route_section or "section").lower().replace(" ", "_")[:48]
        forms.append({
            "name": f"form_{slug}_{rid}",
            "kind": "FORM",
            "filename": f"forms/{slug}_{rid}.html",
            "content": _form_page(pm, project_name),
            "description": f"Application form — {pm.permit_type} ({pm.route_section})",
        })
    return forms
