# Generated by Django 6.0.1 on 2026-02-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignmentjob_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentjob',
            name='layer_name',
        ),
    ]
