# Generated by Django 5.1.15 on 2026-08-10 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignmentjob_layer_name'),
        ('projects', '0011_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentjob',
            name='unique_project_assignment',
        ),
        migrations.AddConstraint(
            model_name='assignmentjob',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'project')), fields=('project', 'assignee'), name='unique_project_assignment'),
        ),
    ]
