# Generated by Django 5.1.15 on 2026-07-23 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_rename_feature_proj_layer_idx_features_project_24b9e2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('duct', 'Existing Duct'), ('chamber', 'Existing Chamber'), ('pole', 'Existing Pole'), ('fibre', 'Existing Fibre'), ('cabinet', 'Existing Cabinet'), ('handhole', 'Existing Handhole'), ('joint', 'Existing Joint')], max_length=20)),
                ('condition', models.CharField(choices=[('reuse_possible', 'Reuse Possible'), ('needs_repair', 'Needs Repair'), ('blocked', 'Blocked'), ('collapsed', 'Collapsed'), ('flooded', 'Flooded'), ('occupied', 'Occupied'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_assets', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existing_assets', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Existing Asset',
                'verbose_name_plural': 'Existing Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('voice_note', 'Voice Note'), ('measurement', 'Measurement'), ('document', 'Document'), ('sketch', 'Sketch')], default='photo', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='survey/evidence/')),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, default='', max_length=50)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_evidence', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_evidence', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Field Evidence',
                'verbose_name_plural': 'Field Evidence',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_distance_m', models.FloatField(blank=True, help_text='Total distance in meters', null=True)),
                ('point_count', models.PositiveIntegerField(default=0)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_traces', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_traces', to='projects.project')),
            ],
            options={
                'verbose_name': 'GPS Trace',
                'verbose_name_plural': 'GPS Traces',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the trace')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='survey.gpstrace')),
            ],
            options={
                'verbose_name': 'GPS Point',
                'verbose_name_plural': 'GPS Points',
                'ordering': ['trace', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazard_type', models.CharField(choices=[('working_at_height', 'Working at Height'), ('confined_space', 'Confined Space'), ('excavation', 'Excavation'), ('traffic_management', 'Traffic Management'), ('high_voltage', 'High Voltage'), ('flood_risk', 'Flood Risk'), ('dog', 'Dog'), ('aggressive_resident', 'Aggressive Resident'), ('private_security', 'Private Security'), ('environmental', 'Environmental Protection'), ('tree_order', 'Tree Preservation Order')], max_length=30)),
                ('mitigation_template', models.CharField(blank=True, choices=[('traffic_lights', 'Traffic Lights'), ('temp_barriers', 'Temporary Barriers'), ('road_closure', 'Road Closure'), ('permit', 'Permit Required'), ('hdd', 'Use HDD Alternative'), ('night_work', 'Night Work'), ('police_assist', 'Police Assistance'), ('tree_officer', 'Tree Officer Approval'), ('env_approval', 'Environmental Approval'), ('utility_locate', 'Utility Locate'), ('cat_scan', 'CAT Scan'), ('trial_hole', 'Trial Hole')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Hazard',
                'verbose_name_plural': 'Hazards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_changes', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_changes', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Survey Change',
                'verbose_name_plural': 'Survey Changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('visited', 'Visited'), ('verified', 'Verified'), ('modified', 'Modified'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_statuses', to=settings.AUTH_USER_MODEL)),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_status', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Survey Status',
                'verbose_name_plural': 'Survey Statuses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('feature_update', 'Feature Update'), ('photo_upload', 'Photo Upload'), ('gps_trace', 'GPS Trace'), ('risk_assessment', 'Risk Assessment'), ('hazard', 'Hazard'), ('trench_classification', 'Trench Classification')], max_length=30)),
                ('entity_id', models.CharField(help_text='ID of the entity on the client', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Full payload to sync')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrenchSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trench_type', models.CharField(choices=[('new_trench', 'New Trench'), ('existing_duct', 'Existing Duct'), ('existing_trench', 'Existing Trench'), ('existing_fibre_route', 'Existing Fibre Route'), ('existing_openreach_duct', 'Existing Openreach Duct'), ('existing_virgin_duct', 'Existing Virgin Duct'), ('hdd_bore', 'HDD Bore'), ('mole_plough', 'Mole Plough'), ('micro_trench', 'Micro Trench'), ('surface_mounted', 'Surface Mounted'), ('pole_route', 'Pole Route')], default='new_trench', max_length=50)),
                ('construction_method', models.CharField(blank=True, choices=[('open_cut', 'Open Cut'), ('trenchless', 'Trenchless'), ('hdd', 'Horizontal Directional Drilling'), ('mole', 'Mole Plough'), ('micro', 'Micro Trenching'), ('aerial', 'Aerial / Pole')], max_length=30, null=True)),
                ('depth_mm', models.PositiveIntegerField(blank=True, help_text='Depth in millimeters', null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, help_text='Width in millimeters', null=True)),
                ('surface_type', models.CharField(blank=True, choices=[('asphalt', 'Asphalt'), ('concrete', 'Concrete'), ('paving', 'Paving'), ('earth', 'Earth'), ('grass', 'Grass')], max_length=30, null=True)),
                ('road_crossing', models.BooleanField(default=False)),
                ('footpath_crossing', models.BooleanField(default=False)),
                ('rail_crossing', models.BooleanField(default=False)),
                ('river_crossing', models.BooleanField(default=False)),
                ('private_property', models.BooleanField(default=False)),
                ('traffic_sensitive', models.BooleanField(default=False)),
                ('permit_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trench_surveys', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trench_surveys', to='projects.feature')),
            ],
            options={
                'verbose_name': 'Trench Survey',
                'verbose_name_plural': 'Trench Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('traffic', 'Traffic'), ('pedestrian', 'Pedestrian'), ('private_land', 'Private Land'), ('tree_roots', 'Tree Roots'), ('concrete_surface', 'Concrete Surface'), ('railway', 'Railway'), ('bridge', 'Bridge'), ('river', 'River'), ('protected_area', 'Protected Area'), ('environmental', 'Environmental'), ('gas_line', 'Gas Line'), ('water_main', 'Water Main'), ('electric_cable', 'Electric Cable'), ('telecom', 'Telecom'), ('asbestos', 'Asbestos'), ('confined_space', 'Confined Space')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('probability', models.CharField(choices=[('rare', 'Rare'), ('possible', 'Possible'), ('likely', 'Likely'), ('certain', 'Certain')], default='possible', max_length=10)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('accepted', 'Accepted'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='projects.feature')),
                ('trench_survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='survey.trenchsurvey')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
