# Generated by Django 5.1.15 on 2026-07-28 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_feature_edited_at_feature_edited_by_feature_geometry'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_id', models.CharField(db_index=True, max_length=255)),
                ('layer_name', models.CharField(max_length=255)),
                ('original_geometry', models.JSONField(blank=True, help_text='Frozen geometry from the HLD feature', null=True)),
                ('original_attributes', models.JSONField(blank=True, help_text='Frozen attributes from the HLD feature', null=True)),
                ('survey_geometry', models.JSONField(help_text='Engineer-edited geometry')),
                ('survey_attributes', models.JSONField(default=dict, help_text='Engineer-edited attributes')),
                ('survey_status', models.CharField(choices=[('new', 'New'), ('modified', 'Modified'), ('removed', 'Removed'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed')], default='new', max_length=20)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('change_reason', models.TextField(blank=True, default='', help_text='Why the engineer made this change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_features', to=settings.AUTH_USER_MODEL)),
                ('original_hld_feature', models.ForeignKey(blank=True, help_text='Original HLD feature this survey feature was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_features', to='projects.feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_features', to='projects.project')),
            ],
            options={
                'verbose_name': 'Survey Feature',
                'verbose_name_plural': 'Survey Features',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'layer_id'], name='survey_surv_project_ea4a72_idx'), models.Index(fields=['original_hld_feature'], name='survey_surv_origina_4910dc_idx'), models.Index(fields=['survey_status'], name='survey_surv_survey__6ffa12_idx'), models.Index(fields=['sync_status'], name='survey_surv_sync_st_a90d82_idx')],
            },
        ),
    ]
