# Generated by Django 5.1.15 on 2026-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfeature',
            name='photo',
            field=models.ImageField(blank=True, help_text='Evidence photo attached to this survey feature', null=True, upload_to='survey_feature_photos/%Y/%m/%d/'),
        ),
    ]
