# Generated by Django 5.1.15 on 2026-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyfeature_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfeature',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Planner/approver notes from the approval decision'),
        ),
    ]
