# Generated by Django 5.1.15 on 2026-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyfeature_review_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfeature',
            name='survey_status',
            field=models.CharField(choices=[('new', 'New'), ('modified', 'Modified'), ('removed', 'Removed'), ('pending_review', 'Pending Review'), ('needs_correction', 'Needs Correction'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
