# Generated by Django 5.1.15 on 2026-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0005_alter_surveyfeature_survey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfeature',
            name='is_removal',
            field=models.BooleanField(default=False),
        ),
    ]
