# Generated by Django 5.1.15 on 2026-08-13 11:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0007_surveyeditlog_rename_surveychange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'decision',
                    models.CharField(
                        choices=[
                            ('approved', 'Approved'),
                            ('rejected', 'Rejected'),
                            ('needs_correction', 'Needs Correction'),
                        ],
                        max_length=20,
                    ),
                ),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'reviewer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'survey_feature',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='approval_records',
                        to='survey.surveyfeature',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Approval Record',
                'verbose_name_plural': 'Approval Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
